### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ghost** [nikosgram13/OglofusProtection#4]
logs
https://gist.github.com/mat41997/32cf3b2d9dc5ac464258e0120df76dd7

timings
https://timings.aikar.co/?id=0570cf120a004f89847ad9adab1a9b9a

torch
https://github.com/TorchSpigot/Torch
https://yivesmirror.com/downloads/torch

**Comment by nikosgram** [comment]
Hey, this plugin doesn't work on 1.11 or older versions of the spigot.

Thank you for the report anyway. 😄
